export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_EMAIL_OTP: '/verify-email-otp',
    RESEND_EMAIL_OTP: '/resend-email-otp',
    FORGOT_PASSWORD: '/forgot-password',
    FORGOT_RESEND_OTP: '/forgot-resend-otp',
    VERIFY_RESET_OTP: '/verify-reset-otp',
    SET_NEW_PASSWORD: '/set-new-password',
    CHANGE_PASSWORD: '/change-password',
    LOGOUT: '/logout',
  },
  COUNTRIES: '/countries',
  PROFILE: '/profile',
  PROFILE_COUNTRY: '/profile/country',
  PROFILE_BASIC_INFO: '/profile/basic-info',
  PROFILE_EDUCATION: '/profile/education',
  PROFILE_PHYSICAL: '/profile/physical',
  PROFILE_CAREER: '/profile/career',
  PROFILE_FAITH: '/profile/faith',
  PROFILE_PHOTOS: '/profile/photos',
  PROFILE_COMPLETE: '/profile/complete',
  PROFILE_PHOTO_VISIBILITY: '/profile/photo-visibility',
  PROFILE_UPDATE: '/profile/update',
  VERIFY_PHONE_SEND: '/verify-phone/send',
  VERIFY_PHONE_RESEND: '/verify-phone/resend',
  VERIFY_PHONE_VERIFY: '/verify-phone/verify',
  VERIFY_PHONE_STATUS: '/verify-phone/status',
  SHORTLIST: '/shortlist',
  REFERRALS_STATS: '/referrals/stats',
  REFERRALS_HISTORY: '/referrals/history',
  REFERRALS_LINK: '/referrals/link',
  REFERRALS_REWARDS: '/referrals/rewards',
  REFERRALS_REDEEM: '/referrals/redeem',
  PHOTO_ACCESS: '/photo-access',
  PHOTO_ACCESS_REQUESTS: '/photo-access-requests',
  photoAccessUserRequest: (userId: string) =>
    `/photo-access/${userId}/request`,
  photoAccessRespond: (requestId: string) =>
    `/photo-access-requests/${requestId}/respond`,
  photoAccessById: (requestId: string) =>
    `/photo-access-requests/${requestId}`,
  NOTIFICATIONS: '/notifications',
  NOTIFICATIONS_READ_ALL: '/notifications/read-all',
  NOTIFICATIONS_CLEAR_ALL: '/notifications/clear-all',
  MATCHES_HOME: '/matches/home',
  MATCHES_BEST: '/matches/best-match',
  MATCHES_SEARCH: '/matches/search',
  MATCHES: '/matches',
  SUBSCRIPTIONS: '/subscriptions',
  SUBSCRIPTIONS_CURRENT: '/subscriptions/current',
  SUBSCRIPTIONS_SUBSCRIBE: '/subscriptions/subscribe',
  ACCOUNT_DEACTIVATE: '/account/deactivate',
  ACCOUNT_DELETE: '/account/delete',
} as const;
